/**
 * Code generation utilities
 */

/** Generate the standard deterministic header for generated files. */
export function generateFileHeader() {
  return `/**
 * Generated by prisma-effect-kysely
 * DO NOT EDIT MANUALLY
 */`;
}
